#!/bin/bash

if [[ $(hostname) = "S-MB-UBUNTU" ]] ; then
	
	alsa_out -j "Output" -d hw:CARD=PCH,DEV=1 &
	sleep 3
	#alsa_in -j "External In" -d plughw:CARD=Set,DEV=0 &
	
	#sleep 2
	alsa_in -j "USB Mic" -d plughw:CARD=MICROPHONE,DEV=0 &
#	~/keyListen.sh
fi

if [[ $(hostname) = "S-D-KUBUNTU" ]] ; then
	alsa_out -j "Output" -d hw:CARD=PCH,DEV=1 &
	sleep 5
	alsa_in -j "USB Mic" -d hw:CARD=MICROPHONE,DEV=0 &

	while [[ "1" == "1" ]] ; do 
		sleep 1
	done
fi

#a2jmidid -e
#killall jackd

